version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:      
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      - network-zabbix
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=192.168.79.87
      - ZBX_SERVER_HOST=192.168.79.87

